import { University } from './models/university.ts';

const universities = [
    {
        name: 'Addis Ababa University',
        slug: 'aau',
        location: { city: 'Addis Ababa', region: 'Addis Ababa' },
        established: 1950,
        type: 'Public',
        description: 'Addis Ababa University is Ethiopia’s oldest and most prestigious public university located in the capital where the weather is generally mild, sunny, and comfortable.',
        website: 'http://www.aau.edu.et',
        contactEmail: 'info@aau.edu.et',
        phone: '+251 11 123 2435',
        coordinates: { lat: 9.0478, lng: 38.7618 },
        faculties: ['Natural Sciences', 'Medicine', 'Engineering', 'Social Sciences'],
        campuses: ['Main Campus (6 Kilo)', 'Science Campus (4 Kilo)', 'Technology Campus (5 Kilo)', 'Black Lion Health Campus'],
        colleges: [
            {
                name: 'Addis Ababa Institute of Technology (AAiT)',
                departments: [
                    { name: 'Software Engineering', duration: '5 Years', description: 'Comprehensive training in software lifecycle, AI, and systems design.' },
                    { name: 'Electrical & Computer Engineering', duration: '5 Years' },
                ],
            },
            {
                name: 'College of Health Sciences',
                departments: [
                    { name: 'Doctor of Medicine (MD)', duration: '6.5 Years' },
                    { name: 'School of Pharmacy', duration: '5 Years' },
                ],
            },
        ],
        facilities: ['Kennedy Library', 'Ethnological Museum', 'ICT Innovation Hub'],
        image: '/assets/aau6.png',
    },
    {
        name: 'Addis Ababa Science & Technology University',
        slug: 'aastu',
        location: { city: 'Addis Ababa', region: 'Addis Ababa' },
        established: 2011,
        type: 'Public',
        description: 'Addis Ababa Science and Technology University is a modern public science-and-technology focused university in Addis Ababa.',
        website: 'http://www.aastu.edu.et',
        contactEmail: 'info@aastu.edu.et',
        phone: '+251 11 869 6052',
        coordinates: { lat: 8.89, lng: 38.8 },
        faculties: ['Engineering', 'Computing', 'Applied Sciences'],
        campuses: ['Kilinto Main Campus'],
        colleges: [
            {
                name: 'College of Electrical & Mechanical Engineering',
                departments: [
                    { name: 'Software Engineering', duration: '5 Years' },
                    { name: 'Mechanical Engineering', duration: '5 Years' },
                ],
            },
        ],
        facilities: ['Center of Excellence in ICT', 'Material Science Lab'],
        image: '/assets/aastu.jpg',
    },
    {
        name: 'Adama Science & Technology University',
        slug: 'astu',
        location: { city: 'Adama', region: 'Oromia' },
        established: 1993,
        type: 'Public',
        description: 'Adama Science and Technology University is a well-established public technical university in Adama.',
        website: 'http://www.astu.edu.et',
        contactEmail: 'info@astu.edu.et',
        phone: '+251 22 110 0001',
        coordinates: { lat: 8.5667, lng: 39.2667 },
        faculties: ['Engineering', 'Applied Science', 'Computing'],
        campuses: ['Main Adama Campus'],
        colleges: [
            {
                name: 'School of Electrical Engineering & Computing',
                departments: [
                    { name: 'Computer Science & Engineering', duration: '5 Years' },
                    { name: 'Electronics & Communication', duration: '5 Years' },
                ],
            },
        ],
        facilities: ['Robotics Center', 'Advanced Nanotechnology Lab'],
        image: '/assets/Astu.png',
    },
    {
        name: 'Jimma University',
        slug: 'ju',
        location: { city: 'Jimma', region: 'Oromia' },
        established: 1952,
        type: 'Public',
        description: 'Jimma University is a respected public university in Jimma known for health sciences and agriculture.',
        website: 'http://www.ju.edu.et',
        contactEmail: 'info@ju.edu.et',
        phone: '+251 47 111 2233',
        coordinates: { lat: 7.675, lng: 36.835 },
        faculties: ['Health Sciences', 'Technology', 'Agriculture', 'Business'],
        campuses: ['Main Campus', 'Agriculture Campus (JUCAVM)', 'Technology Campus (JiT)'],
        colleges: [
            {
                name: 'Jimma Institute of Technology (JiT)',
                departments: [
                    { name: 'Biomedical Engineering', duration: '5 Years' },
                    { name: 'Information Technology', duration: '4 Years' },
                ],
            },
        ],
        facilities: ['Jimma Specialized Hospital', 'Coffee Research Center'],
        image: '/assets/jimma4.png',
    },
    {
        name: 'Bahir Dar University',
        slug: 'bdu',
        location: { city: 'Bahir Dar', region: 'Amhara' },
        established: 1953,
        type: 'Public',
        description: 'Bahir Dar University is a major public university in Bahir Dar with strong engineering and water technology programs.',
        website: 'http://www.bdu.edu.et',
        contactEmail: 'info@bdu.edu.et',
        phone: '+251 58 220 5927',
        coordinates: { lat: 11.5936, lng: 37.3908 },
        faculties: ['Maritime', 'Engineering', 'Textile', 'Medicine'],
        campuses: ['Poly Campus', 'Peda Campus', 'Lake Shore Campus'],
        colleges: [
            {
                name: 'Bahir Dar Institute of Technology (BiT)',
                departments: [
                    { name: 'Textile Engineering', duration: '5 Years' },
                    { name: 'Chemical Engineering', duration: '5 Years' },
                ],
            },
        ],
        facilities: ['Maritime Simulator', 'Lake Tana Research Center'],
        image: '/assets/bahirdar1.png',
    },
    {
        name: 'Hawassa University',
        slug: 'hu',
        location: { city: 'Hawassa', region: 'Sidama' },
        established: 1976,
        type: 'Public',
        description: 'Hawassa University is a well-established public university in Hawassa with strong medicine and agriculture programs.',
        website: 'http://www.hu.edu.et',
        contactEmail: 'info@hu.edu.et',
        phone: '+251 46 220 5311',
        coordinates: { lat: 7.0494, lng: 38.4849 },
        faculties: ['Agriculture', 'Forestry', 'Medicine', 'Law'],
        campuses: ['Main Campus', 'Awada Campus', 'Wondo Genet Campus'],
        colleges: [
            {
                name: 'College of Medicine & Health Sciences',
                departments: [
                    { name: 'Medicine', duration: '6.5 Years' },
                    { name: 'Nursing', duration: '4 Years' },
                ],
            },
        ],
        facilities: ['Referral Hospital', 'Botanical Garden'],
        image: '/assets/hawasau.png',
    },
    {
        name: 'University of Gondar',
        slug: 'uog',
        location: { city: 'Gondar', region: 'Amhara' },
        established: 1954,
        type: 'Public',
        description: 'University of Gondar is a comprehensive public university known for medicine and health sciences.',
        website: 'http://www.uog.edu.et',
        contactEmail: 'info@uog.edu.et',
        phone: '+251 58 111 0123',
        coordinates: { lat: 12.6078, lng: 37.4571 },
        faculties: ['Medicine', 'Public Health', 'Veterinary', 'Informatics'],
        campuses: ['Maraki Campus', 'Tewodros Campus', 'Atse Fasil Campus'],
        colleges: [
            {
                name: 'College of Medicine & Health Sciences',
                departments: [
                    { name: 'Public Health Officer', duration: '4 Years' },
                    { name: 'Medicine', duration: '6.5 Years' },
                ],
            },
        ],
        facilities: ['Gondar Referral Hospital', 'Specialized Eye Clinic'],
        image: '/assets/gonder.png',
    },
    {
        name: 'Mekelle University',
        slug: 'mu',
        location: { city: 'Mekelle', region: 'Tigray' },
        established: 1993,
        type: 'Public',
        description: 'Mekelle University is a major public university in northern Ethiopia known for engineering and agriculture.',
        website: 'http://www.mu.edu.et',
        contactEmail: 'info@mu.edu.et',
        phone: '+251 34 440 7608',
        coordinates: { lat: 13.4967, lng: 39.4682 },
        faculties: ['Dryland Agriculture', 'Law', 'Engineering', 'Business'],
        campuses: ['Arid Campus', 'Adi Haki Campus', 'Ayder Health Campus'],
        colleges: [
            {
                name: 'College of Law & Governance',
                departments: [{ name: 'Law', duration: '5 Years' }],
            },
        ],
        facilities: ['Ayder Referral Hospital', 'Dryland Research Site'],
        image: '/assets/mekelle.jpg',
    },
    {
        name: 'Arba Minch University',
        slug: 'amu',
        location: { city: 'Arba Minch', region: 'SNNP' },
        established: 1986,
        type: 'Public',
        description: 'Arba Minch University is a large public university known for water technology and agriculture.',
        website: 'http://www.amu.edu.et',
        contactEmail: 'info@amu.edu.et',
        phone: '+251 46 881 4986',
        coordinates: { lat: 6.0333, lng: 37.55 },
        faculties: ['Water Technology', 'Natural Science', 'Engineering', 'Agriculture'],
        campuses: ['Main Campus', 'Abaya Campus', 'Chamo Campus'],
        colleges: [
            {
                name: 'Institute of Water Technology',
                departments: [
                    { name: 'Hydraulic Engineering', duration: '5 Years' },
                    { name: 'Water Resources Management', duration: '5 Years' },
                ],
            },
        ],
        facilities: ['Hydraulic Research Lab', 'University Museum'],
        image: '/assets/arbaminch.png',
    },
    {
        name: 'Haramaya University',
        slug: 'hru',
        location: { city: 'Haramaya', region: 'Oromia' },
        established: 1954,
        type: 'Public',
        description: 'Haramaya University is a historic public university in eastern Ethiopia known for agriculture and health sciences.',
        website: 'http://www.haramaya.edu.et',
        contactEmail: 'info@haramaya.edu.et',
        phone: '+251 25 553 0324',
        coordinates: { lat: 9.4, lng: 42.0167 },
        faculties: ['Agriculture', 'Veterinary', 'Health', 'Education'],
        campuses: ['Main Haramaya Campus', 'Harar Health Campus'],
        colleges: [
            {
                name: 'College of Agriculture & Environmental Sciences',
                departments: [
                    { name: 'Animal Science', duration: '4 Years' },
                    { name: 'Plant Science', duration: '4 Years' },
                ],
            },
        ],
        facilities: ['Research Farm', 'Central Library'],
        image: '/assets/haremeya1.png',
    },
    {
        name: 'Dire Dawa University',
        slug: 'ddu',
        location: { city: 'Dire Dawa', region: 'Dire Dawa' },
        established: 2007,
        type: 'Public',
        description: 'Dire Dawa University is a vibrant public university in the industrial city of Dire Dawa.',
        website: 'http://www.ddu.edu.et',
        contactEmail: 'info@ddu.edu.et',
        phone: '+251 25 112 0123',
        coordinates: { lat: 9.6, lng: 41.8667 },
        faculties: ['Business', 'Engineering', 'Social Science', 'Law'],
        campuses: ['Main Campus'],
        colleges: [
            {
                name: 'College of Business & Economics',
                departments: [
                    { name: 'Accounting & Finance', duration: '4 Years' },
                    { name: 'Management', duration: '4 Years' },
                ],
            },
        ],
        facilities: ['Eastern ICT Hub', 'Modern Student Plaza'],
        image: '/assets/diredewa.png',
    },
];

export async function seedUniversities() {
    const count = await University.countDocuments();
    if (count > 0) return count;

    await University.insertMany(universities);
    return universities.length;
}
